/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/CompressedCityScape2.glb -o ./src/DestroyedCity/Models/CitEsc.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Cityscape(props) {
  const { nodes, materials } = useGLTF('/CompressedCityScape2.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed' colliders='trimesh'>
      <mesh geometry={nodes['01PLights01'].geometry} material={materials.PaletteMaterial001} position={[0, 0.409, 150]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.329} />
      </RigidBody>
      <mesh geometry={nodes['03A-TowerA01_G01015'].geometry} material={nodes['03A-TowerA01_G01015'].material} position={[-40, 123.752, 40]} scale={[21.948, 0.98, 19.127]} />
      <instancedMesh args={[nodes.Plane540.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane540.instanceMatrix} />
      <instancedMesh args={[nodes.A01_G02030.geometry, nodes.A01_G02030.material, 2]} instanceMatrix={nodes.A01_G02030.instanceMatrix} />
      <instancedMesh args={[nodes.Plane036.geometry, materials.PaletteMaterial001, 4]} instanceMatrix={nodes.Plane036.instanceMatrix} />
      <instancedMesh args={[nodes.Plane035.geometry, materials.PaletteMaterial001, 3]} instanceMatrix={nodes.Plane035.instanceMatrix} />
      <instancedMesh args={[nodes.Plane311.geometry, materials.PaletteMaterial001, 3]} instanceMatrix={nodes.Plane311.instanceMatrix} />
      <instancedMesh args={[nodes.Plane025.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane025.instanceMatrix} />
      <instancedMesh args={[nodes.A02_W1033.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.A02_W1033.instanceMatrix} />
      <instancedMesh args={[nodes.A02_W1032.geometry, materials.PaletteMaterial001, 3]} instanceMatrix={nodes.A02_W1032.instanceMatrix} />
      <instancedMesh args={[nodes.A02_COL1012.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.A02_COL1012.instanceMatrix} />
      <instancedMesh args={[nodes.Plane264.geometry, nodes.Plane264.material, 2]} instanceMatrix={nodes.Plane264.instanceMatrix} />
      <instancedMesh args={[nodes.A02_W1022.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.A02_W1022.instanceMatrix} />
      <instancedMesh args={[nodes.A02_W1020.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.A02_W1020.instanceMatrix} />
      <instancedMesh args={[nodes.Plane244.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane244.instanceMatrix} />
      <instancedMesh args={[nodes.A01_ST01017.geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes.A01_ST01017.instanceMatrix} />
      <instancedMesh args={[nodes.Circle034.geometry, nodes.Circle034.material, 2]} instanceMatrix={nodes.Circle034.instanceMatrix} />
      <instancedMesh args={[nodes.Circle033.geometry, nodes.Circle033.material, 2]} instanceMatrix={nodes.Circle033.instanceMatrix} />
      <instancedMesh args={[nodes.A02_W2019.geometry, materials.PaletteMaterial001, 3]} instanceMatrix={nodes.A02_W2019.instanceMatrix} />
      <instancedMesh args={[nodes.A02_W1019.geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes.A02_W1019.instanceMatrix} />
      <instancedMesh args={[nodes.A01_W1011.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.A01_W1011.instanceMatrix} />
      <instancedMesh args={[nodes.A01_D1010.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.A01_D1010.instanceMatrix} />
      <instancedMesh args={[nodes.A01_W1010.geometry, materials.PaletteMaterial001, 4]} instanceMatrix={nodes.A01_W1010.instanceMatrix} />
      <instancedMesh args={[nodes.A01_ST04003.geometry, nodes.A01_ST04003.material, 2]} instanceMatrix={nodes.A01_ST04003.instanceMatrix} />
      <instancedMesh args={[nodes.A01_ST05003.geometry, nodes.A01_ST05003.material, 2]} instanceMatrix={nodes.A01_ST05003.instanceMatrix} />
      <instancedMesh args={[nodes.A02_ST02009.geometry, nodes.A02_ST02009.material, 2]} instanceMatrix={nodes.A02_ST02009.instanceMatrix} />
      <instancedMesh args={[nodes.A02_W1017.geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes.A02_W1017.instanceMatrix} />
      <instancedMesh args={[nodes.A01_G01010.geometry, materials.PaletteMaterial001, 4]} instanceMatrix={nodes.A01_G01010.instanceMatrix} />
      <instancedMesh args={[nodes.A01_G02021.geometry, materials.PaletteMaterial001, 3]} instanceMatrix={nodes.A01_G02021.instanceMatrix} />
      <instancedMesh args={[nodes.A01_G02020.geometry, materials.PaletteMaterial001, 3]} instanceMatrix={nodes.A01_G02020.instanceMatrix} />
      <instancedMesh args={[nodes.Plane133.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane133.instanceMatrix} />
      <instancedMesh args={[nodes.Plane113.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane113.instanceMatrix} />
      <instancedMesh args={[nodes.Plane018.geometry, nodes.Plane018.material, 2]} instanceMatrix={nodes.Plane018.instanceMatrix} />
      <instancedMesh args={[nodes.Plane008.geometry, nodes.Plane008.material, 2]} instanceMatrix={nodes.Plane008.instanceMatrix} />
      <instancedMesh args={[nodes.A01_G01.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.A01_G01.instanceMatrix} />
      <instancedMesh args={[nodes['100_Building01100_Sol01'].geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes['100_Building01100_Sol01'].instanceMatrix} />
      <instancedMesh args={[nodes['101_Bulding101_Bulding101_BuldingCircle015'].geometry, materials.PaletteMaterial001, 3]} instanceMatrix={nodes['101_Bulding101_Bulding101_BuldingCircle015'].instanceMatrix} />
      <instancedMesh args={[nodes['101_BuldingCircle011'].geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes['101_BuldingCircle011'].instanceMatrix} />
      <instancedMesh args={[nodes.Circle061.geometry, nodes.Circle061.material, 2]} instanceMatrix={nodes.Circle061.instanceMatrix} />
      <instancedMesh args={[nodes.Circle055.geometry, nodes.Circle055.material, 3]} instanceMatrix={nodes.Circle055.instanceMatrix} />
      <instancedMesh args={[nodes.Plane1116.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane1116.instanceMatrix} />
      <instancedMesh args={[nodes.Plane054.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane054.instanceMatrix} />
      <instancedMesh args={[nodes.Plane051.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane051.instanceMatrix} />
      <instancedMesh args={[nodes.Plane021.geometry, nodes.Plane021.material, 2]} instanceMatrix={nodes.Plane021.instanceMatrix} />
      <instancedMesh args={[nodes.Circle122.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Circle122.instanceMatrix} />
      <instancedMesh args={[nodes.Plane1150.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane1150.instanceMatrix} />
      <instancedMesh args={[nodes.Plane1149.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane1149.instanceMatrix} />
      <instancedMesh args={[nodes.Plane1142.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane1142.instanceMatrix} />
      <instancedMesh args={[nodes.A02_W1031.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.A02_W1031.instanceMatrix} />
      <instancedMesh args={[nodes.A02_W1031_1.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.A02_W1031_1.instanceMatrix} />
      <instancedMesh args={[nodes.A01_D1009.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.A01_D1009.instanceMatrix} />
      <instancedMesh args={[nodes.A01_D1009_1.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.A01_D1009_1.instanceMatrix} />
      <instancedMesh args={[nodes.A02_W1018.geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes.A02_W1018.instanceMatrix} />
      <instancedMesh args={[nodes.A02_W1018_1.geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes.A02_W1018_1.instanceMatrix} />
      <instancedMesh args={[nodes.A02_W1016.geometry, materials.PaletteMaterial001, 3]} instanceMatrix={nodes.A02_W1016.instanceMatrix} />
      <instancedMesh args={[nodes.A02_W1016_1.geometry, materials.PaletteMaterial001, 3]} instanceMatrix={nodes.A02_W1016_1.instanceMatrix} />
      <instancedMesh args={[nodes.A02_W1015.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.A02_W1015.instanceMatrix} />
      <instancedMesh args={[nodes.A02_W1015_1.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.A02_W1015_1.instanceMatrix} />
      <instancedMesh args={[nodes.Plane106.geometry, materials.PaletteMaterial001, 4]} instanceMatrix={nodes.Plane106.instanceMatrix} />
      <instancedMesh args={[nodes.Plane106_1.geometry, materials.PaletteMaterial001, 4]} instanceMatrix={nodes.Plane106_1.instanceMatrix} />
      <instancedMesh args={[nodes.Plane102.geometry, materials.PaletteMaterial001, 4]} instanceMatrix={nodes.Plane102.instanceMatrix} />
      <instancedMesh args={[nodes.Plane102_1.geometry, materials.PaletteMaterial001, 4]} instanceMatrix={nodes.Plane102_1.instanceMatrix} />
      <instancedMesh args={[nodes.Plane097.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane097.instanceMatrix} />
      <instancedMesh args={[nodes.Plane097_1.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane097_1.instanceMatrix} />
      <instancedMesh args={[nodes.Cube002.geometry, nodes.Cube002.material, 2]} instanceMatrix={nodes.Cube002.instanceMatrix} />
      <instancedMesh args={[nodes.Cube002_1.geometry, nodes.Cube002_1.material, 2]} instanceMatrix={nodes.Cube002_1.instanceMatrix} />
      <instancedMesh args={[nodes.Cube002_2.geometry, nodes.Cube002_2.material, 2]} instanceMatrix={nodes.Cube002_2.instanceMatrix} />
      <instancedMesh args={[nodes.Plane914.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane914.instanceMatrix} />
      <instancedMesh args={[nodes.Plane914_1.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane914_1.instanceMatrix} />
      <instancedMesh args={[nodes.Plane914_2.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane914_2.instanceMatrix} />
      <instancedMesh args={[nodes.Plane914_3.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane914_3.instanceMatrix} />
      <instancedMesh args={[nodes.Plane914_4.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane914_4.instanceMatrix} />
      <instancedMesh args={[nodes.Plane914_5.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane914_5.instanceMatrix} />
      <instancedMesh args={[nodes.Plane914_6.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane914_6.instanceMatrix} />
      <instancedMesh args={[nodes.Plane914_7.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane914_7.instanceMatrix} />
      <instancedMesh args={[nodes.Plane019.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane019.instanceMatrix} />
      <instancedMesh args={[nodes.Plane019_1.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane019_1.instanceMatrix} />
      <instancedMesh args={[nodes.Plane019_2.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane019_2.instanceMatrix} />
      <instancedMesh args={[nodes.Plane019_3.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane019_3.instanceMatrix} />
      <instancedMesh args={[nodes.Plane019_4.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane019_4.instanceMatrix} />
      <instancedMesh args={[nodes.Plane019_5.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane019_5.instanceMatrix} />
      <instancedMesh args={[nodes.Plane019_6.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane019_6.instanceMatrix} />
      <instancedMesh args={[nodes.Plane019_7.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Plane019_7.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/CompressedCityScape2.glb')
