/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/DestroyedCity.glb -o ./src/DestroyedCity/Models/DestroyedCityModel.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function DestroyedCityModel(props) {
  const { nodes, materials } = useGLTF('/DestroyedCity.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.856, -14.557]} scale={0.01}>
        <group position={[0, 652.299, 1455.725]} rotation={[Math.PI / 2, 0, 0]} scale={37.472}>
          <mesh geometry={nodes.Mesh036.geometry} material={materials['Blasted01.001']} />
          <mesh geometry={nodes.Mesh036_1.geometry} material={materials['BlastedGlass.001']} />
          <mesh geometry={nodes.Mesh036_2.geometry} material={materials['Blasted02.001']} />
          <mesh geometry={nodes.Mesh036_3.geometry} material={materials.BurgerBase01} />
          <mesh geometry={nodes.Mesh036_4.geometry} material={materials.BurgerSigns02} />
          <mesh geometry={nodes.Mesh036_5.geometry} material={materials.BurgerSigns03} />
          <mesh geometry={nodes.Mesh036_6.geometry} material={materials.Burger01} />
          <mesh geometry={nodes.Mesh036_7.geometry} material={materials.BurgerGlass} />
          <mesh geometry={nodes.Mesh036_8.geometry} material={materials.BurgerSigns01} />
          <mesh geometry={nodes.Mesh036_9.geometry} material={materials.GasStation01} />
          <mesh geometry={nodes.Mesh036_10.geometry} material={materials.GasStation03} />
          <mesh geometry={nodes.Mesh036_11.geometry} material={materials.GasStation02} />
          <mesh geometry={nodes.Mesh036_12.geometry} material={materials.GasStation00} />
          <mesh geometry={nodes.Mesh036_13.geometry} material={materials.GasStation04} />
          <mesh geometry={nodes.Mesh036_14.geometry} material={materials.GasStation06} />
          <mesh geometry={nodes.Mesh036_15.geometry} material={materials.MegaBlock01} />
          <mesh geometry={nodes.Mesh036_16.geometry} material={materials.MegaBlockGlass} />
          <mesh geometry={nodes.Mesh036_17.geometry} material={materials.B1GLASS} />
          <mesh geometry={nodes.Mesh036_18.geometry} material={materials.B1BGLASS} />
          <mesh geometry={nodes.Mesh036_19.geometry} material={materials.Rubble01} />
          <mesh geometry={nodes.Mesh036_20.geometry} material={materials.HotelM1} />
          <mesh geometry={nodes.Mesh036_21.geometry} material={materials.HotelM1gLASS} />
          <mesh geometry={nodes.Mesh036_22.geometry} material={materials.HotelB1Outside} />
          <mesh geometry={nodes.Mesh036_23.geometry} material={materials.HOTELBSignage} />
          <mesh geometry={nodes.Mesh036_24.geometry} material={materials.HotelB1Inside} />
          <mesh geometry={nodes.Mesh036_25.geometry} material={materials.HotelB1GLASS} />
          <mesh geometry={nodes.Mesh036_26.geometry} material={materials.HotelC1} />
          <mesh geometry={nodes.Mesh036_27.geometry} material={materials.HotelC1GLASS} />
          <mesh geometry={nodes.Mesh036_28.geometry} material={materials.HOTELA1} />
          <mesh geometry={nodes.Mesh036_29.geometry} material={materials.HOTELA1GLASS} />
          <RigidBody type='fixed'>
          <mesh geometry={nodes.Mesh036_30.geometry} material={materials['RoadBase.001']} />
          <mesh geometry={nodes.Mesh036_31.geometry} material={materials['GroundBase.001']} />
          </RigidBody>
          <mesh geometry={nodes.Mesh036_32.geometry} material={materials['TBA02.001']} />
          <mesh geometry={nodes.Mesh036_33.geometry} material={materials['TBA02windows.001']} />
          <mesh geometry={nodes.Mesh036_34.geometry} material={materials.G02} />
          <mesh geometry={nodes.Mesh036_35.geometry} material={materials.G03} />
          <RigidBody type='fixed' colliders='trimesh'>
          <mesh geometry={nodes.Mesh036_36.geometry} material={materials.BRIDGE}/> 
          </RigidBody>
          <mesh geometry={nodes.Mesh036_37.geometry} material={materials['1']} />
          <mesh geometry={nodes.Mesh036_38.geometry} material={materials['2']} />
          <mesh geometry={nodes.Mesh036_39.geometry} material={materials['3']} />
          <mesh geometry={nodes.Mesh036_40.geometry} material={materials['4']} />
          <mesh geometry={nodes.Mesh036_41.geometry} material={materials['5']} />
          <mesh geometry={nodes.Mesh036_42.geometry} material={materials['6']} />
          <mesh geometry={nodes.Mesh036_43.geometry} material={materials['7']} />
          <mesh geometry={nodes.Mesh036_44.geometry} material={materials['8']} />
          <mesh geometry={nodes.Mesh036_45.geometry} material={materials['9']} />
          <mesh geometry={nodes.Mesh036_46.geometry} material={materials['10']} />
          <mesh geometry={nodes.Mesh036_47.geometry} material={materials['11']} />
          <RigidBody type='fixed' colliders='trimesh'>
          <mesh geometry={nodes.Mesh036_48.geometry} material={materials['12']} />
          <mesh geometry={nodes.Mesh036_49.geometry} material={materials.Mat} />
          </RigidBody>
          <mesh geometry={nodes.Mesh036_50.geometry} material={materials.light1} />
          <mesh geometry={nodes.Mesh036_51.geometry} material={materials.light2} />
        </group>
      </group>
      <group position={[63.653, 2.856, -14.557]} scale={0.01}>
        <group position={[0, 652.299, 1455.725]} rotation={[Math.PI / 2, 0, 0]} scale={37.472}>
          <group position={[5.354, 0, 0]}>
            <mesh geometry={nodes.Mesh002.geometry} material={materials['Blasted01.003']} />
            <mesh geometry={nodes.Mesh002_1.geometry} material={materials['BlastedGlass.003']} />
            <mesh geometry={nodes.Mesh002_2.geometry} material={materials['Blasted02.003']} />
            <mesh geometry={nodes.Mesh002_3.geometry} material={materials['BurgerBase01.002']} />
            <mesh geometry={nodes.Mesh002_4.geometry} material={materials['BurgerSigns02.002']} />
            <mesh geometry={nodes.Mesh002_5.geometry} material={materials['BurgerSigns03.002']} />
            <mesh geometry={nodes.Mesh002_6.geometry} material={materials['Burger01.002']} />
            <mesh geometry={nodes.Mesh002_7.geometry} material={materials['BurgerGlass.002']} />
            <mesh geometry={nodes.Mesh002_8.geometry} material={materials['BurgerSigns01.002']} />
            <mesh geometry={nodes.Mesh002_9.geometry} material={materials['GasStation01.002']} />
            <mesh geometry={nodes.Mesh002_10.geometry} material={materials['GasStation03.002']} />
            <mesh geometry={nodes.Mesh002_11.geometry} material={materials['GasStation02.002']} />
            <mesh geometry={nodes.Mesh002_12.geometry} material={materials['GasStation00.002']} />
            <mesh geometry={nodes.Mesh002_13.geometry} material={materials['GasStation04.002']} />
            <mesh geometry={nodes.Mesh002_14.geometry} material={materials['GasStation06.002']} />
            <mesh geometry={nodes.Mesh002_15.geometry} material={materials['MegaBlock01.002']} />
            <mesh geometry={nodes.Mesh002_16.geometry} material={materials['MegaBlockGlass.002']} />
            <mesh geometry={nodes.Mesh002_17.geometry} material={materials['B1GLASS.002']} />
            <mesh geometry={nodes.Mesh002_18.geometry} material={materials['B1BGLASS.002']} />
            <mesh geometry={nodes.Mesh002_19.geometry} material={materials['Rubble01.002']} />
            <mesh geometry={nodes.Mesh002_20.geometry} material={materials['HotelM1.002']} />
            <mesh geometry={nodes.Mesh002_21.geometry} material={materials['HotelM1gLASS.002']} />
            <mesh geometry={nodes.Mesh002_22.geometry} material={materials['HotelB1Outside.002']} />
            <mesh geometry={nodes.Mesh002_23.geometry} material={materials['HOTELBSignage.002']} />
            <mesh geometry={nodes.Mesh002_24.geometry} material={materials['HotelB1Inside.002']} />
            <mesh geometry={nodes.Mesh002_25.geometry} material={materials['HotelB1GLASS.002']} />
            <mesh geometry={nodes.Mesh002_26.geometry} material={materials['HotelC1.002']} />
            <mesh geometry={nodes.Mesh002_27.geometry} material={materials['HotelC1GLASS.002']} />
            <mesh geometry={nodes.Mesh002_28.geometry} material={materials['HOTELA1.002']} />
            <mesh geometry={nodes.Mesh002_29.geometry} material={materials['HOTELA1GLASS.002']} />
            <RigidBody type='fixed'>
            <mesh geometry={nodes.Mesh002_30.geometry} material={materials['RoadBase.003']} />
            <mesh geometry={nodes.Mesh002_31.geometry} material={materials['GroundBase.003']} />
            </RigidBody>
            <mesh geometry={nodes.Mesh002_32.geometry} material={materials['TBA02.003']} />
            <mesh geometry={nodes.Mesh002_33.geometry} material={materials['TBA02windows.003']} />
            <mesh geometry={nodes.Mesh002_34.geometry} material={materials['G02.002']} />
            <mesh geometry={nodes.Mesh002_35.geometry} material={materials['G03.002']} />
            <RigidBody type='fixed' colliders='trimesh'>
            <mesh geometry={nodes.Mesh002_36.geometry} material={materials['BRIDGE.002']} />
            </RigidBody>
            <mesh geometry={nodes.Mesh002_37.geometry} material={materials['1.002']}/>
            <mesh geometry={nodes.Mesh002_38.geometry} material={materials['2.002']} />
            <mesh geometry={nodes.Mesh002_39.geometry} material={materials['3.002']} />
            <mesh geometry={nodes.Mesh002_40.geometry} material={materials['4.002']} />
            <mesh geometry={nodes.Mesh002_41.geometry} material={materials['5.002']} />
            <mesh geometry={nodes.Mesh002_42.geometry} material={materials['6.002']} />
            <mesh geometry={nodes.Mesh002_43.geometry} material={materials['7.002']}  />
            <mesh geometry={nodes.Mesh002_44.geometry} material={materials['8.002']} />
            <mesh geometry={nodes.Mesh002_45.geometry} material={materials['9.002']} />
            <mesh geometry={nodes.Mesh002_46.geometry} material={materials['10.002']} />
            <mesh geometry={nodes.Mesh002_47.geometry} material={materials['11.002']} />
            <RigidBody type='fixed' colliders='trimesh'>
            <mesh geometry={nodes.Mesh002_48.geometry} material={materials['12.002']} />
            <mesh geometry={nodes.Mesh002_49.geometry} material={materials['Mat.002']} />
            </RigidBody>
            <mesh geometry={nodes.Mesh002_50.geometry} material={materials['light1.002']} />
            <mesh geometry={nodes.Mesh002_51.geometry} material={materials['light2.002']} />
          </group>
        </group>
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials.agua2} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['agua2.002']} position={[63.653, 0, 0]} />
      <RigidBody type='fixed'>
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.001']} position={[31.887, 2.865, -11.945]} scale={[2.7, 1, 18]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.002']} position={[32.55, 3.156, 8.342]} scale={[1, 1, 3]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.003']} position={[32.55, 3.275, 27.254]} scale={[1, 1, 3]} />
      </RigidBody>
    </group>
  )
}

