/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/AdultKrishnaAnimated.glb -o ./src/ModernCity/Models/AdultKrishna.jsx 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function AdultKrishna(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/AdultKrishnaAnimated.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names} = useAnimations(animations, group)
  useEffect(()=>{
    actions[names[0]].reset().fadeIn(.5).play()
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Dasavataram_Character_-_WIP-_Lord_Vishnu001" position={[2.208, 0, 0]}>
          <group name="RootNode001">
            <group name="Dasavataram_Full_Body001">
              <group name="group19001">
                <group name="pasted__pTorus1001" />
              </group>
            </group>
          </group>
        </group>
        <group name="Dasavataram_Character_-_WIP-_Lord_Vishnu">
          <group name="RootNode1">
            <group name="Dasavataram_Full_Body">
              <group name="eyes_all">
                <group name="group29">
                  <group name="group20">
                    <group name="Leye3" />
                    <group name="Leye4" />
                  </group>
                  <group name="group21">
                    <group name="Leye1" />
                    <group name="Leye2" />
                  </group>
                  <group name="group22">
                    <group name="Leye1001" />
                    <group name="Leye2001" />
                  </group>
                  <group name="group23">
                    <group name="Leye1002" />
                    <group name="Leye2002" />
                  </group>
                  <group name="group24">
                    <group name="Leye1003" />
                    <group name="Leye2003" />
                  </group>
                  <group name="group25">
                    <group name="Leye1004" />
                    <group name="Leye2004" />
                  </group>
                  <group name="group26">
                    <group name="Leye1005" />
                    <group name="Leye2005" />
                  </group>
                  <group name="group27">
                    <group name="Leye1006" />
                    <group name="Leye2006" />
                  </group>
                  <group name="group28">
                    <group name="Leye1007" />
                    <group name="Leye2007" />
                  </group>
                </group>
                <group name="group30">
                  <group name="group20001">
                    <group name="Leye3001" />
                    <group name="Leye4001" />
                  </group>
                  <group name="group21001">
                    <group name="Leye1008" />
                    <group name="Leye2008" />
                  </group>
                  <group name="group22001">
                    <group name="Leye1009" />
                    <group name="Leye2009" />
                  </group>
                  <group name="group23001">
                    <group name="Leye1010" />
                    <group name="Leye2010" />
                  </group>
                  <group name="group24001">
                    <group name="Leye1011" />
                    <group name="Leye2011" />
                  </group>
                  <group name="group25001">
                    <group name="Leye1012" />
                    <group name="Leye2012" />
                  </group>
                  <group name="group26001">
                    <group name="Leye1013" />
                    <group name="Leye2013" />
                  </group>
                  <group name="group27001">
                    <group name="Leye1014" />
                    <group name="Leye2014" />
                  </group>
                  <group name="group28001">
                    <group name="Leye1015" />
                    <group name="Leye2015" />
                  </group>
                </group>
                <group name="Leye" />
                <group name="Reye" />
              </group>
              <group name="group10">
                <group name="pasted__pasted__pasted__pasted__polySurface5" />
                <group name="pasted__polySurface2529" />
                <group name="pasted__polySurface2530" />
                <group name="pasted__polySurface2531" />
                <group name="polySurface1072" />
              </group>
              <group name="group11">
                <group name="pasted__pasted__pasted__pasted__polySurface19" />
                <group name="pasted__polySurface2544" />
                <group name="pasted__polySurface2545" />
                <group name="pasted__polySurface2546" />
                <group name="polySurface1077" />
                <group name="polySurface849" />
              </group>
              <group name="group12">
                <group name="pasted__pasted__pasted__pasted__polySurface18" />
                <group name="pasted__polySurface2541" />
                <group name="pasted__polySurface2542" />
                <group name="pasted__polySurface2543" />
                <group name="polySurface1076" />
                <group name="polySurface848" />
              </group>
              <group name="group13">
                <group name="pasted__pasted__pasted__pasted__polySurface17" />
                <group name="pasted__polySurface1992" />
                <group name="pasted__polySurface2538" />
                <group name="pasted__polySurface2539" />
                <group name="pasted__polySurface2540" />
                <group name="polySurface1075" />
                <group name="polySurface847" />
              </group>
              <group name="group14">
                <group name="pasted__pasted__pasted__pasted__polySurface16" />
                <group name="pasted__polySurface2535" />
                <group name="pasted__polySurface2536" />
                <group name="pasted__polySurface2537" />
                <group name="polySurface1074" />
                <group name="polySurface846" />
              </group>
              <group name="group15">
                <group name="pasted__polySurface2524" />
                <group name="pasted__pTorus10" />
                <group name="pasted__pTorus9" />
                <group name="polySurface1382" />
              </group>
              <group name="group16">
                <group name="pasted__pasted__pasted__pasted__polySurface15" />
                <group name="pasted__polySurface1540" />
                <group name="polySurface1079" />
                <group name="polySurface839" />
                <group name="polySurface844" />
                <group name="polySurface845" />
              </group>
              <group name="group17">
                <group name="pasted__pasted__pasted__pasted__polySurface14" />
                <group name="polySurface1078" />
                <group name="polySurface825" />
                <group name="polySurface827" />
                <group name="polySurface833" />
              </group>
              <group name="group18">
                <group name="pasted__pasted__pasted__pasted__polySurface13" />
                <group name="pasted__polySurface1242" />
                <group name="pasted__polySurface2503" />
                <group name="pasted__polySurface2523" />
                <group name="polySurface1073" />
              </group>
              <group name="group19">
                <group name="pasted__pasted__polySurface8825" />
                <group name="pasted__polySurface1297" />
                <group name="pasted__polySurface1488" />
                <group name="pasted__pTorus1" />
                <group name="pasted__pTorus2" />
                <group name="pasted__pTorus4" />
              </group>
              <group name="group2">
                <group name="hairr" />
                <group name="pasted__polySurface1224" />
                <group name="pasted__polySurface2571" />
                <group name="pasted__polySurface2572" />
                <group name="pasted__polySurface2573" />
                <group name="polySurface853" />
                <group name="polySurface855" />
              </group>
              <group name="group3">
                <group name="pasted__pasted__pasted__pasted__polySurface11" />
                <group name="pasted__polySurface2565" />
                <group name="pasted__polySurface2569" />
                <group name="pasted__polySurface2570" />
                <group name="polySurface1383" />
                <group name="polySurface852" />
              </group>
              <group name="group31">
                <group name="hair_mid" />
                <group name="Head" />
                <group name="poly_kirit1" />
                <group name="poly_kirit2" />
                <group name="poly_kirit3" />
                <group name="poly_kirit4" />
                <group name="poly_kirit5" />
                <group name="polySurface1165" />
                <group name="polySurface1302" />
                <group name="polySurface1303" />
                <group name="polySurface1329" />
                <group name="polySurface1345" />
                <group name="polySurface1346" />
                <group name="polySurface1347" />
                <group name="polySurface1376" />
                <group name="polySurface1377" />
                <group name="polySurface1378" />
                <group name="polySurface1384" />
                <group name="polySurface1386" />
                <group name="polySurface1388" />
                <group name="polySurface814" />
                <group name="polySurface815" />
                <group name="tongue" />
              </group>
              <group name="group4">
                <group name="pasted__pasted__pasted__pasted__polySurface10" />
                <group name="pasted__polySurface2547" />
                <group name="pasted__polySurface2548" />
                <group name="pasted__polySurface2549" />
                <group name="pasted__polySurface2550" />
                <group name="polySurface1379" />
                <group name="polySurface851" />
              </group>
              <group name="group5">
                <group name="pasted__pasted__pasted__pasted__polySurface9" />
                <group name="pasted__polySurface2555" />
                <group name="pasted__polySurface2556" />
                <group name="pasted__polySurface2559" />
                <group name="pasted__polySurface2560" />
                <group name="polySurface1381" />
                <group name="polySurface850" />
              </group>
              <group name="group6">
                <group name="pasted__polySurface2574" />
                <group name="pasted__polySurface679" />
                <group name="pasted__polySurface680" />
                <group name="pasted__polySurface681" />
                <group name="pasted__polySurface688" />
                <group name="pasted__polySurface697" />
                <group name="pasted__polySurface706" />
                <group name="pasted__polySurface707" />
                <group name="pasted__polySurface708" />
                <group name="pasted__pTorus5" />
                <group name="pasted__pTorus6" />
                <group name="pasted__pTorus7" />
                <group name="pasted__pTorus8" />
                <group name="polySurface829" />
              </group>
              <group name="group7">
                <group name="pasted__pasted__pasted__pasted__polySurface8" />
                <group name="pasted__pasted__polySurface1496" />
                <group name="pasted__polySurface689" />
                <group name="pasted__polySurface698" />
                <group name="polySurface1068" />
              </group>
              <group name="group8">
                <group name="pasted__pasted__pasted__pasted__polySurface7" />
                <group name="pasted__polySurface2532" />
                <group name="pasted__polySurface2533" />
                <group name="pasted__polySurface2534" />
                <group name="polySurface1069" />
                <group name="polySurface854" />
              </group>
              <group name="group9">
                <group name="pasted__pasted__pasted__pasted__polySurface6" />
                <group name="pasted__polySurface2516" />
                <group name="pasted__polySurface2526" />
                <group name="polySurface1070" />
              </group>
            </group>
          </group>
        </group>
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="hair_mid_Hair3_0" geometry={nodes.hair_mid_Hair3_0.geometry} material={materials.Hair3} skeleton={nodes.hair_mid_Hair3_0.skeleton} />
          <skinnedMesh name="Head_Body2_0" geometry={nodes.Head_Body2_0.geometry} material={materials.Body2} skeleton={nodes.Head_Body2_0.skeleton} />
          <skinnedMesh name="Leye_Tiger_Man_Final_mesh_3M_Eyes_0" geometry={nodes.Leye_Tiger_Man_Final_mesh_3M_Eyes_0.geometry} material={materials['Tiger_Man_Final_mesh_3:M_Eyes']} skeleton={nodes.Leye_Tiger_Man_Final_mesh_3M_Eyes_0.skeleton} />
          <skinnedMesh name="pasted__polySurface2529_g1Gold2_0" geometry={nodes.pasted__polySurface2529_g1Gold2_0.geometry} material={materials['g1:Gold2']} skeleton={nodes.pasted__polySurface2529_g1Gold2_0.skeleton} />
          <skinnedMesh name="pasted__polySurface2529_ggreener_stone1_0" geometry={nodes.pasted__polySurface2529_ggreener_stone1_0.geometry} material={materials['g:greener_stone1']} skeleton={nodes.pasted__polySurface2529_ggreener_stone1_0.skeleton} />
          <skinnedMesh name="pasted__polySurface2529_ggreenstonegreener_stone1_0" geometry={nodes.pasted__polySurface2529_ggreenstonegreener_stone1_0.geometry} material={materials['g:greenstone:greener_stone1']} skeleton={nodes.pasted__polySurface2529_ggreenstonegreener_stone1_0.skeleton} />
          <skinnedMesh name="pasted__pTorus1_g1Gold2_0" geometry={nodes.pasted__pTorus1_g1Gold2_0.geometry} material={materials['g1:Gold2']} skeleton={nodes.pasted__pTorus1_g1Gold2_0.skeleton} />
          <skinnedMesh name="pasted__pTorus1_g1Gold2_0001" geometry={nodes.pasted__pTorus1_g1Gold2_0001.geometry} material={materials['g1:Gold2.001']} skeleton={nodes.pasted__pTorus1_g1Gold2_0001.skeleton} />
          <skinnedMesh name="poly_kirit1_g1Gold2_0" geometry={nodes.poly_kirit1_g1Gold2_0.geometry} material={materials['g1:Gold2']} skeleton={nodes.poly_kirit1_g1Gold2_0.skeleton} />
          <skinnedMesh name="poly_kirit1_ggreener_stone1_0" geometry={nodes.poly_kirit1_ggreener_stone1_0.geometry} material={materials['g:greener_stone1']} skeleton={nodes.poly_kirit1_ggreener_stone1_0.skeleton} />
          <skinnedMesh name="poly_kirit1_ggreenstonegreener_stone1_0" geometry={nodes.poly_kirit1_ggreenstonegreener_stone1_0.geometry} material={materials['g:greenstone:greener_stone1']} skeleton={nodes.poly_kirit1_ggreenstonegreener_stone1_0.skeleton} />
          <skinnedMesh name="poly_kirit2_Flower_1_0" geometry={nodes.poly_kirit2_Flower_1_0.geometry} material={materials.Flower_1} skeleton={nodes.poly_kirit2_Flower_1_0.skeleton} />
          <skinnedMesh name="poly_kirit3_Cloth_2_0" geometry={nodes.poly_kirit3_Cloth_2_0.geometry} material={materials.Cloth_2} skeleton={nodes.poly_kirit3_Cloth_2_0.skeleton} />
          <skinnedMesh name="poly_kirit4_Pancha1_0" geometry={nodes.poly_kirit4_Pancha1_0.geometry} material={materials.Pancha1} skeleton={nodes.poly_kirit4_Pancha1_0.skeleton} />
          <skinnedMesh name="poly_kirit5_Cloth_5_0" geometry={nodes.poly_kirit5_Cloth_5_0.geometry} material={materials.Cloth_5} skeleton={nodes.poly_kirit5_Cloth_5_0.skeleton} />
          <skinnedMesh name="polySurface1072_blinn1_0" geometry={nodes.polySurface1072_blinn1_0.geometry} material={materials.blinn1} skeleton={nodes.polySurface1072_blinn1_0.skeleton} />
          <skinnedMesh name="polySurface1165_blinn1_0" geometry={nodes.polySurface1165_blinn1_0.geometry} material={materials.blinn1} skeleton={nodes.polySurface1165_blinn1_0.skeleton} />
          <skinnedMesh name="polySurface1165_g1Gold2_0" geometry={nodes.polySurface1165_g1Gold2_0.geometry} material={materials['g1:Gold2']} skeleton={nodes.polySurface1165_g1Gold2_0.skeleton} />
          <skinnedMesh name="polySurface1165_ggreener_stone1_0" geometry={nodes.polySurface1165_ggreener_stone1_0.geometry} material={materials['g:greener_stone1']} skeleton={nodes.polySurface1165_ggreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1165_ggreenstonegreener_stone1_0" geometry={nodes.polySurface1165_ggreenstonegreener_stone1_0.geometry} material={materials['g:greenstone:greener_stone1']} skeleton={nodes.polySurface1165_ggreenstonegreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1302_g1Gold2_0" geometry={nodes.polySurface1302_g1Gold2_0.geometry} material={materials['g1:Gold2']} skeleton={nodes.polySurface1302_g1Gold2_0.skeleton} />
          <skinnedMesh name="polySurface1302_ggreener_stone1_0" geometry={nodes.polySurface1302_ggreener_stone1_0.geometry} material={materials['g:greener_stone1']} skeleton={nodes.polySurface1302_ggreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1302_ggreenstonegreener_stone1_0" geometry={nodes.polySurface1302_ggreenstonegreener_stone1_0.geometry} material={materials['g:greenstone:greener_stone1']} skeleton={nodes.polySurface1302_ggreenstonegreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1303_g1Gold2_0" geometry={nodes.polySurface1303_g1Gold2_0.geometry} material={materials['g1:Gold2']} skeleton={nodes.polySurface1303_g1Gold2_0.skeleton} />
          <skinnedMesh name="polySurface1303_ggreener_stone1_0" geometry={nodes.polySurface1303_ggreener_stone1_0.geometry} material={materials['g:greener_stone1']} skeleton={nodes.polySurface1303_ggreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1303_ggreenstonegreener_stone1_0" geometry={nodes.polySurface1303_ggreenstonegreener_stone1_0.geometry} material={materials['g:greenstone:greener_stone1']} skeleton={nodes.polySurface1303_ggreenstonegreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1329_g1Gold2_0" geometry={nodes.polySurface1329_g1Gold2_0.geometry} material={materials['g1:Gold2']} skeleton={nodes.polySurface1329_g1Gold2_0.skeleton} />
          <skinnedMesh name="polySurface1329_ggreener_stone1_0" geometry={nodes.polySurface1329_ggreener_stone1_0.geometry} material={materials['g:greener_stone1']} skeleton={nodes.polySurface1329_ggreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1329_ggreenstonegreener_stone1_0" geometry={nodes.polySurface1329_ggreenstonegreener_stone1_0.geometry} material={materials['g:greenstone:greener_stone1']} skeleton={nodes.polySurface1329_ggreenstonegreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1345_g1Gold2_0" geometry={nodes.polySurface1345_g1Gold2_0.geometry} material={materials['g1:Gold2']} skeleton={nodes.polySurface1345_g1Gold2_0.skeleton} />
          <skinnedMesh name="polySurface1345_ggreener_stone1_0" geometry={nodes.polySurface1345_ggreener_stone1_0.geometry} material={materials['g:greener_stone1']} skeleton={nodes.polySurface1345_ggreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1345_ggreenstonegreener_stone1_0" geometry={nodes.polySurface1345_ggreenstonegreener_stone1_0.geometry} material={materials['g:greenstone:greener_stone1']} skeleton={nodes.polySurface1345_ggreenstonegreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1346_g1Gold2_0" geometry={nodes.polySurface1346_g1Gold2_0.geometry} material={materials['g1:Gold2']} skeleton={nodes.polySurface1346_g1Gold2_0.skeleton} />
          <skinnedMesh name="polySurface1346_ggreener_stone1_0" geometry={nodes.polySurface1346_ggreener_stone1_0.geometry} material={materials['g:greener_stone1']} skeleton={nodes.polySurface1346_ggreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1346_ggreenstonegreener_stone1_0" geometry={nodes.polySurface1346_ggreenstonegreener_stone1_0.geometry} material={materials['g:greenstone:greener_stone1']} skeleton={nodes.polySurface1346_ggreenstonegreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1347_g1Gold2_0" geometry={nodes.polySurface1347_g1Gold2_0.geometry} material={materials['g1:Gold2']} skeleton={nodes.polySurface1347_g1Gold2_0.skeleton} />
          <skinnedMesh name="polySurface1347_ggreener_stone1_0" geometry={nodes.polySurface1347_ggreener_stone1_0.geometry} material={materials['g:greener_stone1']} skeleton={nodes.polySurface1347_ggreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1347_ggreenstonegreener_stone1_0" geometry={nodes.polySurface1347_ggreenstonegreener_stone1_0.geometry} material={materials['g:greenstone:greener_stone1']} skeleton={nodes.polySurface1347_ggreenstonegreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1376_g1Gold2_0" geometry={nodes.polySurface1376_g1Gold2_0.geometry} material={materials['g1:Gold2']} skeleton={nodes.polySurface1376_g1Gold2_0.skeleton} />
          <skinnedMesh name="polySurface1376_ggreener_stone1_0" geometry={nodes.polySurface1376_ggreener_stone1_0.geometry} material={materials['g:greener_stone1']} skeleton={nodes.polySurface1376_ggreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1376_ggreenstonegreener_stone1_0" geometry={nodes.polySurface1376_ggreenstonegreener_stone1_0.geometry} material={materials['g:greenstone:greener_stone1']} skeleton={nodes.polySurface1376_ggreenstonegreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1377_g1Gold2_0" geometry={nodes.polySurface1377_g1Gold2_0.geometry} material={materials['g1:Gold2']} skeleton={nodes.polySurface1377_g1Gold2_0.skeleton} />
          <skinnedMesh name="polySurface1377_ggreener_stone1_0" geometry={nodes.polySurface1377_ggreener_stone1_0.geometry} material={materials['g:greener_stone1']} skeleton={nodes.polySurface1377_ggreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1377_ggreenstonegreener_stone1_0" geometry={nodes.polySurface1377_ggreenstonegreener_stone1_0.geometry} material={materials['g:greenstone:greener_stone1']} skeleton={nodes.polySurface1377_ggreenstonegreener_stone1_0.skeleton} />
          <skinnedMesh name="polySurface1378_Flower_1_0" geometry={nodes.polySurface1378_Flower_1_0.geometry} material={materials.Flower_1} skeleton={nodes.polySurface1378_Flower_1_0.skeleton} />
          <skinnedMesh name="polySurface1378_Flower_1_0001" geometry={nodes.polySurface1378_Flower_1_0001.geometry} material={materials.Flower_1} skeleton={nodes.polySurface1378_Flower_1_0001.skeleton} />
          <skinnedMesh name="polySurface1384_Body2_0" geometry={nodes.polySurface1384_Body2_0.geometry} material={materials.Body2} skeleton={nodes.polySurface1384_Body2_0.skeleton} />
          <skinnedMesh name="polySurface1384_Nails1_0" geometry={nodes.polySurface1384_Nails1_0.geometry} material={materials.Nails1} skeleton={nodes.polySurface1384_Nails1_0.skeleton} />
          <skinnedMesh name="polySurface1386_Body2_0" geometry={nodes.polySurface1386_Body2_0.geometry} material={materials.Body2} skeleton={nodes.polySurface1386_Body2_0.skeleton} />
          <skinnedMesh name="polySurface1386_Nails1_0" geometry={nodes.polySurface1386_Nails1_0.geometry} material={materials.Nails1} skeleton={nodes.polySurface1386_Nails1_0.skeleton} />
          <skinnedMesh name="polySurface1388_Body2_0" geometry={nodes.polySurface1388_Body2_0.geometry} material={materials.Body2} skeleton={nodes.polySurface1388_Body2_0.skeleton} />
          <skinnedMesh name="polySurface1388_Nails1_0" geometry={nodes.polySurface1388_Nails1_0.geometry} material={materials.Nails1} skeleton={nodes.polySurface1388_Nails1_0.skeleton} />
          <skinnedMesh name="polySurface814_blinn1_0" geometry={nodes.polySurface814_blinn1_0.geometry} material={materials.blinn1} skeleton={nodes.polySurface814_blinn1_0.skeleton} />
          <skinnedMesh name="polySurface815_blinn1_0" geometry={nodes.polySurface815_blinn1_0.geometry} material={materials.blinn1} skeleton={nodes.polySurface815_blinn1_0.skeleton} />
          <skinnedMesh name="Reye_Tiger_Man_Final_mesh_3M_Eyes_0" geometry={nodes.Reye_Tiger_Man_Final_mesh_3M_Eyes_0.geometry} material={materials['Tiger_Man_Final_mesh_3:M_Eyes']} skeleton={nodes.Reye_Tiger_Man_Final_mesh_3M_Eyes_0.skeleton} />
          <skinnedMesh name="tongue_blinn1_0" geometry={nodes.tongue_blinn1_0.geometry} material={materials.blinn1} skeleton={nodes.tongue_blinn1_0.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/AdultKrishnaAnimated.glb')
