

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Janis Zeps (https://sketchfab.com/Zeps3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/telephone-booth-ea3e24f9738a49319df879df55752c94
Title: Telephone Booth
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Booth (props) {
  const { nodes, materials } = useGLTF('/Telephone_comp_opt.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-4.911, -0.164, -5.238]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0.geometry}
          material={materials.background}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_1.geometry}
          material={materials.booth}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_2.geometry}
          material={materials.glass}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Telephone_comp_opt.glb')