/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2022-ferrari-daytona-sp3-36f271240bfd47d9aca48c2903703d6e
Title: 2022 Ferrari Daytona SP3
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HyperCar2(props) {
  const { nodes, materials } = useGLTF('/CarHyper2_comp.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Badge_Geo_lodA_Ferrari_DaytonaSP3_2022BadgeA_Material_0.geometry}
        material={materials.Ferrari_DaytonaSP3_2022BadgeA_Material}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Base_Geo_lodA_Ferrari_DaytonaSP3_2022Base_Material_0.geometry}
        material={materials.PaletteMaterial001}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Carbon1M_Geo_lodA_Ferrari_DaytonaSP3_2022Carbon1_Material_0.geometry}
        material={materials.Ferrari_DaytonaSP3_2022Carbon1_Material}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Coloured_Geo_lodA_Ferrari_DaytonaSP3_2022Coloured_Material_0.geometry}
        material={materials.PaletteMaterial002}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Engine_Geo_lodA_Ferrari_DaytonaSP3_2022EngineA_Material_0.geometry}
        material={materials.Ferrari_DaytonaSP3_2022EngineA_Material}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grille1_Geo_lodA_Ferrari_DaytonaSP3_2022Grille1A_Material_0.geometry}
        material={materials.Ferrari_DaytonaSP3_2022Grille1A_Material}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grille2_Geo_lodA_Ferrari_DaytonaSP3_2022Grille2A_Material_0.geometry}
        material={materials.Ferrari_DaytonaSP3_2022Grille2A_Material}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grille3_Geo_lodA_Ferrari_DaytonaSP3_2022Grille3A_Material_0.geometry}
        material={materials.Ferrari_DaytonaSP3_2022Grille3A_Material}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grille4_Geo_lodA_Ferrari_DaytonaSP3_2022Grille4A_Material_0.geometry}
        material={materials.Ferrari_DaytonaSP3_2022Grille4A_Material}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grille5_Geo_lodA_Ferrari_DaytonaSP3_2022Grille5A_Material_0.geometry}
        material={materials.Ferrari_DaytonaSP3_2022Grille5A_Material}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grille6_Geo_lodA_Ferrari_DaytonaSP3_2022Grille6A_Material_0.geometry}
        material={materials.Ferrari_DaytonaSP3_2022Grille6A_Material}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.InteriorTilling_Geo_lodA_Ferrari_DaytonaSP3_2022InteriorTillingA_Material_0.geometry
        }
        material={materials.Ferrari_DaytonaSP3_2022InteriorTillingA_Material}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Interior_Geo_lodA_Ferrari_DaytonaSP3_2022InteriorA_Material_0.geometry}
        material={materials.Ferrari_DaytonaSP3_2022InteriorA_Material}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.LightEmissive_Geo_lodA_Ferrari_DaytonaSP3_2022LightEmissiveA_Material_0.geometry
        }
        material={materials.Ferrari_DaytonaSP3_2022LightEmissiveA_Material}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Light_Geo_lodA_Ferrari_DaytonaSP3_2022LightA_Material_0.geometry}
        material={materials.Ferrari_DaytonaSP3_2022LightA_Material}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.ManufacturerPlate_Geo_lodA_Ferrari_DaytonaSP3_2022ManufacturerPlateA_Material_0
            .geometry
        }
        material={materials.Ferrari_DaytonaSP3_2022ManufacturerPlateA_Material}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paint_Geo_lodA_Ferrari_DaytonaSP3_2022Paint_Material_0.geometry}
        material={materials.PaletteMaterial003}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SeatBelt_Geo_lodA_Ferrari_DaytonaSP3_2022SeatBelt_Material_0.geometry}
        material={materials.PaletteMaterial004}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WindowInside_Geo_lodA_Ferrari_DaytonaSP3_2022Window_Material_0.geometry}
        material={materials.PaletteMaterial005}
        position={[0, 0.001, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.polySurface1_Ferrari_DaytonaSP3_2022_Wheel1A_3D_3DWheel1A_Material_0.geometry
        }
        material={materials.Ferrari_DaytonaSP3_2022_Wheel1A_3D_3DWheel1A_Material}
        position={[0.008, 0.003, 0.012]}
        rotation={[0, 0, 0.026]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.polySurface519_Ferrari_DaytonaSP3_2022_CallipersCalliperA_Zone_Material_0.geometry
        }
        material={materials.Ferrari_DaytonaSP3_2022_CallipersCalliperA_Zone_Material}
        position={[0.008, 0.003, 0.012]}
        rotation={[0, 0, 0.026]}
        scale={0.01}
      />
    </group>
  )
}

useGLTF.preload('/CarHyper2_comp.glb')
