/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2026-zenvo-aurora-tur-a9420f263dac41e99e42112c122987a8
Title: 2026 Zenvo Aurora Tur
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HyperCar1(props) {
  const { nodes, materials } = useGLTF('/CarHyper1_comp.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Badge_Geo_lodA_Zenvo_AuroraTur_2024BadgeA_Material_0.geometry}
        material={materials.Zenvo_AuroraTur_2024BadgeA_Material}
        position={[0, 0.001, 0]}
        rotation={[0.003, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Base_Geo_lodA_Zenvo_AuroraTur_2024Base_Material_0.geometry}
        material={materials.PaletteMaterial001}
        position={[0, 0.001, 0]}
        rotation={[0.003, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Coloured_Geo_lodA_Zenvo_AuroraTur_2024Coloured_Material_0.geometry}
        material={materials.PaletteMaterial002}
        position={[0, 0.001, 0]}
        rotation={[0.003, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GrilleAlpha1_Geo_lodA_Zenvo_AuroraTur_2024GrilleAlpha1A_Material_0.geometry}
        material={materials.Zenvo_AuroraTur_2024GrilleAlpha1A_Material}
        position={[0, 0.001, 0]}
        rotation={[0.003, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.GrilleNoAlpha2_Geo_lodA_Zenvo_AuroraTur_2024GrilleNoAlpha2A_Material_0.geometry
        }
        material={materials.Zenvo_AuroraTur_2024GrilleNoAlpha2A_Material}
        position={[0, 0.001, 0]}
        rotation={[0.003, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.GrilleNoAlpha3_Geo_lodA_Zenvo_AuroraTur_2024GrilleNoAlpha3A_Material_0.geometry
        }
        material={materials.Zenvo_AuroraTur_2024GrilleNoAlpha3A_Material}
        position={[0, 0.001, 0]}
        rotation={[0.003, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.InteriorColourZone_Geo_lodA_Zenvo_AuroraTur_2024InteriorColourZoneA_Material_0
            .geometry
        }
        material={materials.Zenvo_AuroraTur_2024InteriorColourZoneA_Material}
        position={[0, 0.001, 0]}
        rotation={[0.003, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Interior_Geo_lodA_Zenvo_AuroraTur_2024InteriorA_Material_0.geometry}
        material={materials.Zenvo_AuroraTur_2024InteriorA_Material}
        position={[0, 0.001, 0]}
        rotation={[0.003, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Kit0_Carbon1_Geo_lodA_Zenvo_AuroraTur_2024Carbon1_Material_0.geometry}
        material={materials.Zenvo_AuroraTur_2024Carbon1_Material}
        position={[0, 0.001, 0]}
        rotation={[0.003, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.LightEmissive_Geo_lodA_Zenvo_AuroraTur_2024LightEmissiveA_Material_0.geometry
        }
        material={materials.Zenvo_AuroraTur_2024LightEmissiveA_Material}
        position={[0, 0.001, 0]}
        rotation={[0.003, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Light_Geo_lodA_Zenvo_AuroraTur_2024LightA_Material_0.geometry}
        material={materials.Zenvo_AuroraTur_2024LightA_Material}
        position={[0, 0.001, 0]}
        rotation={[0.003, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.ManufacturerPlate_Geo_lodA_Zenvo_AuroraTur_2024ManufacturerPlateA_Material_0
            .geometry
        }
        material={materials.Zenvo_AuroraTur_2024ManufacturerPlateA_Material}
        position={[0, 0.001, 0]}
        rotation={[0.003, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SeatBelt_Geo_lodA_Zenvo_AuroraTur_2024SeatBelt_Material_0.geometry}
        material={materials.PaletteMaterial003}
        position={[0, 0.001, 0]}
        rotation={[0.003, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WindowInside_Geo_lodA_Zenvo_AuroraTur_2024Window_Material_0.geometry}
        material={materials.PaletteMaterial004}
        position={[0, 0.001, 0]}
        rotation={[0.003, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bodyPaint_Geo_lodABody_lodA_Zenvo_AuroraTur_2024Paint_Material_0.geometry}
        material={materials.PaletteMaterial005}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface1_Zenvo_AuroraTur_2024_Wheel1A_3D_3DWheel1A_Material_0.geometry}
        material={materials.Zenvo_AuroraTur_2024_Wheel1A_3D_3DWheel1A_Material}
        position={[0.008, 0.003, 0.013]}
        rotation={[0, 0, 0.026]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.polySurface121_Zenvo_AuroraTur_2024_Wheel1A_3D_3DWheel1A_Material_0.geometry
        }
        material={materials.Zenvo_AuroraTur_2024_Wheel1A_3D_3DWheel1A_Material}
        position={[0.008, 0.003, 0.013]}
        rotation={[0, 0, 0.026]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.polySurface501_Zenvo_AuroraTur_2024_CallipersCalliperA_Zone_Material_0.geometry
        }
        material={materials.Zenvo_AuroraTur_2024_CallipersCalliperA_Zone_Material}
        position={[0.008, 0.003, 0.013]}
        rotation={[0, 0, 0.026]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.polySurface503_Zenvo_AuroraTur_2024_CallipersCalliperA_Zone_Material_0.geometry
        }
        material={materials.Zenvo_AuroraTur_2024_CallipersCalliperA_Zone_Material}
        position={[0.008, 0.003, 0.013]}
        rotation={[0, 0, 0.026]}
        scale={0.01}
      />
    </group>
  )
}

