/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Disco(props) {
  const { nodes, materials } = useGLTF('/Disco2.glb')
  return (
    <group {...props} dispose={null}>
      <group
        position={[-4.496, 0.02, 0.708]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.254, 0.084, 0.254]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_1.geometry}
          material={materials['Burlington Leather']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_2.geometry}
          material={materials['Material.003']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials['Mosaic 01']}
        position={[0.202, -0.072, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.009']}
        position={[-1.578, 0.274, -3.878]}
        scale={0.254}
      />
      <group
        position={[-4.744, 0.51, -3.522]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.112, 0.214, 0.533]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_1.geometry}
          material={materials['Material.007']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials['Material.004']}
        position={[-4.416, 0.126, -3.57]}
        scale={[0.084, 0.139, 0.692]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={nodes.Cube011.material}
        position={[-4.416, 0.674, -3.57]}
        scale={[0.084, 0.021, 0.692]}
      />
      <group position={[-3.208, 0.696, -4.202]} rotation={[Math.PI / 2, 0, 0]} scale={0.254}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_1.geometry}
          material={materials['Material.010']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Disco2.glb')
