/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 打螺丝 (https://sketchfab.com/youoyouyou)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gas-pump-add0f902b9164718bd0540e88bf9927e
Title: gas pump
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Gas_pump(props) {
  const { nodes, materials } = useGLTF('/gas_pump.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_Material001_0.geometry}
          material={materials['Material.001']}
          position={[-25.401, 135.63, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

