/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/equiped_house1.glb -o ./src/ModernCity/Models/house.jsx 
Author: Isaak_ME (https://sketchfab.com/Isaak_me)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/equiped-house-187ed73a9b934b32800d68d6936b0051
Title: Equiped House
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function House(props) {
  const { nodes, materials } = useGLTF('/equiped_house1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.Merged_materials} scale={0.002} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.coverlet} scale={0.002} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.coverlet_0} scale={0.002} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.coverlet_1} scale={0.002} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.ship2} scale={0.002} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.coverlet_2} scale={0.002} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.coverlet_3} scale={0.002} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.coverlet_4} scale={0.002} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.coverlet_5} scale={0.002} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.upperCabinetDoor} scale={0.002} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.coverlet_6} scale={0.002} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.sink} scale={0.002} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.coverlet_7} scale={0.002} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.coverlet_8} scale={0.002} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.Grey_Plastic} scale={0.002} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.shower_handle} scale={0.002} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.ship2_0} scale={0.002} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.ship2_1} scale={0.002} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.cabinetPane} scale={0.002} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.coverlet_9} scale={0.002} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.sink_0} scale={0.002} />
      <mesh geometry={nodes.Object_92.geometry} material={materials['1721']} scale={0.002} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.coverlet_10} scale={0.002} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.coverlet_11} scale={0.002} />
      <mesh geometry={nodes.Object_100.geometry} material={materials.upperCabinetDoor_0} scale={0.002} />
      <mesh geometry={nodes.Object_148.geometry} material={materials.coverlet_12} scale={0.002} />
      <mesh geometry={nodes.Object_158.geometry} material={materials.mattress} scale={0.002} />
      <mesh geometry={nodes.Object_160.geometry} material={materials.Frame_out} position={[1.687, 0.868, -0.339]} scale={0.002} />
      <mesh geometry={nodes.Object_162.geometry} material={materials.Glass} scale={0.002} />
      <mesh geometry={nodes.Object_164.geometry} material={materials.mattress_0} scale={0.002} />
      <mesh geometry={nodes.Object_170.geometry} material={materials.mattress_1} scale={0.002} />
      <mesh geometry={nodes.Object_174.geometry} material={materials.mattress_2} scale={0.002} />
      <mesh geometry={nodes.Object_178.geometry} material={materials.Glass_0} scale={0.002} />
      <mesh geometry={nodes.Object_180.geometry} material={materials.coverlet_13} scale={0.002} />
      <mesh geometry={nodes.Object_186.geometry} material={materials.coverlet_14} scale={0.002} />
      <mesh geometry={nodes.Object_190.geometry} material={materials.lamp} scale={0.002} />
      <mesh geometry={nodes.Object_192.geometry} material={materials.Door_Borders} scale={0.002} />
      <mesh geometry={nodes.Object_194.geometry} material={materials.lamp_0} scale={0.002} />
      <mesh geometry={nodes.Object_196.geometry} material={materials.coverlet_15} scale={0.002} />
      <mesh geometry={nodes.Object_198.geometry} material={materials.material} scale={0.002} />
      <mesh geometry={nodes.Object_200.geometry} material={materials.coverlet_16} scale={0.002} />
      <mesh geometry={nodes.Object_202.geometry} material={materials.wood_2238} scale={0.002} />
      <mesh geometry={nodes.Object_204.geometry} material={materials.wood_2238_0} scale={0.002} />
      <mesh geometry={nodes.Object_206.geometry} material={materials.mattress_3} scale={0.002} />
      <mesh geometry={nodes.Object_208.geometry} material={materials.coverlet_17} scale={0.002} />
      <mesh geometry={nodes.Object_210.geometry} material={materials['1633']} scale={0.002} />
      <mesh geometry={nodes.Object_212.geometry} material={materials['1634']} scale={0.002} />
      <mesh geometry={nodes.Object_214.geometry} material={materials.mattress_Cube_1636} scale={0.002} />
      <mesh geometry={nodes.Object_224.geometry} material={materials.whitewood} scale={0.002} />
      <mesh geometry={nodes.Object_228.geometry} material={materials.Water} scale={0.002} />
      <mesh geometry={nodes.Object_230.geometry} material={materials.ship2_2} scale={0.002} />
      <mesh geometry={nodes.Object_232.geometry} material={materials.Glass_safety} scale={0.002} />
      <mesh geometry={nodes.Object_238.geometry} material={materials.coverlet_18} scale={0.002} />
      <mesh geometry={nodes.Object_242.geometry} material={materials.ship2_3} scale={0.002} />
      <mesh geometry={nodes.Object_254.geometry} material={materials.coverlet_19} scale={0.002} />
      <mesh geometry={nodes.Object_260.geometry} material={materials.ship2_4} scale={0.002} />
      <mesh geometry={nodes.Object_264.geometry} material={materials.sink_1} scale={0.002} />
      <mesh geometry={nodes.Object_266.geometry} material={materials['1721_0']} scale={0.002} />
      <mesh geometry={nodes.Object_274.geometry} material={materials.towel_1} scale={0.002} />
      <mesh geometry={nodes.Object_278.geometry} material={materials.glass_sweethome3d_window_pane_1782} scale={0.002} />
      <mesh geometry={nodes.Object_286.geometry} material={materials['1808']} scale={0.002} />
      <mesh geometry={nodes.Object_309.geometry} material={materials['2199']} scale={0.002} />
      <mesh geometry={nodes.Object_313.geometry} material={materials.taronja} scale={0.002} />
      <mesh geometry={nodes.Object_315.geometry} material={materials.coverlet_20} scale={0.002} />
      <mesh geometry={nodes.Object_317.geometry} material={materials.coverlet_21} scale={0.002} />
      <mesh geometry={nodes.Object_323.geometry} material={materials['2BNX13D07_1_1']} scale={0.002} />
      <mesh geometry={nodes.Object_333.geometry} material={materials['1721_1']} scale={0.002} />
      <mesh geometry={nodes.Object_341.geometry} material={materials.contour} scale={0.002} />
      <mesh geometry={nodes.Object_343.geometry} material={materials.coverlet_22} scale={0.002} />
      <mesh geometry={nodes.Object_345.geometry} material={materials.ship2_5} scale={0.002} />
      <mesh geometry={nodes.Object_349.geometry} material={materials.wood_2238_1} scale={0.002} />
      <mesh geometry={nodes.Object_351.geometry} material={materials.upperCabinetDoor_1} scale={0.002} />
      <mesh geometry={nodes.Object_353.geometry} material={materials.coverlet_23} scale={0.002} />
      <mesh geometry={nodes.Object_359.geometry} material={materials.teeth} scale={0.002} />
      <mesh geometry={nodes.Object_361.geometry} material={materials.fldkgrey} scale={0.002} />
      <mesh geometry={nodes.Object_363.geometry} material={materials.archwhite} scale={0.002} />
      <mesh geometry={nodes.Object_365.geometry} material={materials.flwhite} scale={0.002} />
      <mesh geometry={nodes.Object_375.geometry} material={materials.bone2} scale={0.002} />
      <mesh geometry={nodes.Object_381.geometry} material={materials.dkblue} scale={0.002} />
      <mesh geometry={nodes.Object_387.geometry} material={materials.lighttan2} scale={0.002} />
      <mesh geometry={nodes.Object_389.geometry} material={materials['2375']} scale={0.002} />
      <mesh geometry={nodes.Object_391.geometry} material={materials.coverlet_24} scale={0.002} />
      <mesh geometry={nodes.Object_393.geometry} material={materials.glass_2379} scale={0.002} />
      <mesh geometry={nodes.Object_395.geometry} material={materials.piece_1_Cube_1_1_1} scale={0.002} />
      <mesh geometry={nodes.Object_399.geometry} material={materials.cristal_limpio} scale={0.002} />
      <mesh geometry={nodes.Object_401.geometry} material={materials.alumain} scale={0.002} />
      <mesh geometry={nodes.Object_403.geometry} material={materials['1721_2']} scale={0.002} />
      <mesh geometry={nodes.Object_405.geometry} material={materials.verde} scale={0.002} />
      <mesh geometry={nodes.Object_407.geometry} material={materials.coverlet_25} scale={0.002} />
      <mesh geometry={nodes.Object_411.geometry} material={materials.Bezel} scale={0.002} />
      <mesh geometry={nodes.Object_415.geometry} material={materials.Screen} scale={0.002} />
      <mesh geometry={nodes.Object_417.geometry} material={materials.blackcabin6460_3_3} scale={0.002} />
      <mesh geometry={nodes.Object_419.geometry} material={materials.Black_paint} scale={0.002} />
      <mesh geometry={nodes.Object_423.geometry} material={materials.brzskin} scale={0.002} />
      <mesh geometry={nodes.Object_425.geometry} material={materials.material_94} scale={0.002} />
      <mesh geometry={nodes.Object_427.geometry} material={materials['1721_3']} scale={0.002} />
      <mesh geometry={nodes.Object_463.geometry} material={materials.Lamp} scale={0.002} />
      <mesh geometry={nodes.Object_465.geometry} material={materials.Glass_4_4_2528} scale={0.002} />
      <mesh geometry={nodes.Object_467.geometry} material={materials.lamp_1} scale={0.002} />
      <mesh geometry={nodes.Object_469.geometry} material={materials.coverlet_26} position={[1.705, 1.754, -0.424]} scale={0.002} />
    </group>
  )
}


