/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/LittlekrishnaAnimated.glb -o ./src/ModernCity/Models/LittleKrishna.jsx 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function LittleKrishna(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/LittlekrishnaAnimated.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names} = useAnimations(animations, group)
  useEffect(()=>{
    actions[names[0]].reset().fadeIn(.5).play()
  },[])
  console.log(names)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Lord_Krishna_-_3D_character_Model">
          <group name="RootNode1">
            <group name="Body" />
            <group name="dhoti_upper" />
            <group name="eye_l" />
            <group name="eye_r" />
            <group name="eyebrow_l" />
            <group name="eyebrow_r" />
            <group name="eyelesh_l" />
            <group name="eyelesh_r" />
            <group name="feather_picock" />
            <group name="garland" />
            <group name="hair" />
            <group name="hair_moti" />
            <group name="hand_kada_l" />
            <group name="hand_kada_r" />
            <group name="jewellary" />
            <group name="leg_kada_l" />
            <group name="leg_kada_r" />
            <group name="lower_teeht" />
            <group name="main_dhoti" />
            <group name="Toung" />
            <group name="upper_teeth1" />
          </group>
        </group>
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Body_krishna_model_iBody1_0" geometry={nodes.Body_krishna_model_iBody1_0.geometry} material={materials['krishna_model_i:Body1']} skeleton={nodes.Body_krishna_model_iBody1_0.skeleton} />
          <skinnedMesh name="dhoti_upper_krishna_model_iDhoti_Front_RED_0" geometry={nodes.dhoti_upper_krishna_model_iDhoti_Front_RED_0.geometry} material={materials['krishna_model_i:Dhoti_Front_RED']} skeleton={nodes.dhoti_upper_krishna_model_iDhoti_Front_RED_0.skeleton} />
          <skinnedMesh name="eye_l_krishna_model_iaiStandardSurface5_0" geometry={nodes.eye_l_krishna_model_iaiStandardSurface5_0.geometry} material={materials['krishna_model_i:aiStandardSurface5']} skeleton={nodes.eye_l_krishna_model_iaiStandardSurface5_0.skeleton} />
          <skinnedMesh name="eye_r_krishna_model_iaiStandardSurface5_0" geometry={nodes.eye_r_krishna_model_iaiStandardSurface5_0.geometry} material={materials['krishna_model_i:aiStandardSurface5']} skeleton={nodes.eye_r_krishna_model_iaiStandardSurface5_0.skeleton} />
          <skinnedMesh name="eyebrow_l_krishna_model_iaiStandardHair1_0" geometry={nodes.eyebrow_l_krishna_model_iaiStandardHair1_0.geometry} material={materials['krishna_model_i:aiStandardHair1']} skeleton={nodes.eyebrow_l_krishna_model_iaiStandardHair1_0.skeleton} />
          <skinnedMesh name="eyebrow_r_krishna_model_iaiStandardHair1_0" geometry={nodes.eyebrow_r_krishna_model_iaiStandardHair1_0.geometry} material={materials['krishna_model_i:aiStandardHair1']} skeleton={nodes.eyebrow_r_krishna_model_iaiStandardHair1_0.skeleton} />
          <skinnedMesh name="eyelesh_l_krishna_model_iaiStandardHair1_0" geometry={nodes.eyelesh_l_krishna_model_iaiStandardHair1_0.geometry} material={materials['krishna_model_i:aiStandardHair1']} skeleton={nodes.eyelesh_l_krishna_model_iaiStandardHair1_0.skeleton} />
          <skinnedMesh name="eyelesh_r_krishna_model_iaiStandardHair1_0" geometry={nodes.eyelesh_r_krishna_model_iaiStandardHair1_0.geometry} material={materials['krishna_model_i:aiStandardHair1']} skeleton={nodes.eyelesh_r_krishna_model_iaiStandardHair1_0.skeleton} />
          <skinnedMesh name="feather_picock_krishna_model_ifeather_0" geometry={nodes.feather_picock_krishna_model_ifeather_0.geometry} material={materials['krishna_model_i:feather']} skeleton={nodes.feather_picock_krishna_model_ifeather_0.skeleton} />
          <skinnedMesh name="garland_krishna_model_iflower_garland_0" geometry={nodes.garland_krishna_model_iflower_garland_0.geometry} material={materials['krishna_model_i:flower_garland']} skeleton={nodes.garland_krishna_model_iflower_garland_0.skeleton} />
          <skinnedMesh name="hair_krishna_model_iaiStandardHair1_0" geometry={nodes.hair_krishna_model_iaiStandardHair1_0.geometry} material={materials['krishna_model_i:aiStandardHair1']} skeleton={nodes.hair_krishna_model_iaiStandardHair1_0.skeleton} />
          <skinnedMesh name="hair_moti_krishna_model_ijewellery1_0" geometry={nodes.hair_moti_krishna_model_ijewellery1_0.geometry} material={materials['krishna_model_i:jewellery1']} skeleton={nodes.hair_moti_krishna_model_ijewellery1_0.skeleton} />
          <skinnedMesh name="hand_kada_l_krishna_model_ijewellery1_0" geometry={nodes.hand_kada_l_krishna_model_ijewellery1_0.geometry} material={materials['krishna_model_i:jewellery1']} skeleton={nodes.hand_kada_l_krishna_model_ijewellery1_0.skeleton} />
          <skinnedMesh name="hand_kada_r_krishna_model_ijewellery1_0" geometry={nodes.hand_kada_r_krishna_model_ijewellery1_0.geometry} material={materials['krishna_model_i:jewellery1']} skeleton={nodes.hand_kada_r_krishna_model_ijewellery1_0.skeleton} />
          <skinnedMesh name="jewellary_krishna_model_ijewellery1_0" geometry={nodes.jewellary_krishna_model_ijewellery1_0.geometry} material={materials['krishna_model_i:jewellery1']} skeleton={nodes.jewellary_krishna_model_ijewellery1_0.skeleton} />
          <skinnedMesh name="leg_kada_l_krishna_model_ijewellery1_0" geometry={nodes.leg_kada_l_krishna_model_ijewellery1_0.geometry} material={materials['krishna_model_i:jewellery1']} skeleton={nodes.leg_kada_l_krishna_model_ijewellery1_0.skeleton} />
          <skinnedMesh name="leg_kada_r_krishna_model_ijewellery1_0" geometry={nodes.leg_kada_r_krishna_model_ijewellery1_0.geometry} material={materials['krishna_model_i:jewellery1']} skeleton={nodes.leg_kada_r_krishna_model_ijewellery1_0.skeleton} />
          <skinnedMesh name="lower_teeht_krishna_model_iTeeth_tounggumSG1_0" geometry={nodes.lower_teeht_krishna_model_iTeeth_tounggumSG1_0.geometry} material={materials['krishna_model_i:Teeth_toung:gumSG1']} skeleton={nodes.lower_teeht_krishna_model_iTeeth_tounggumSG1_0.skeleton} />
          <skinnedMesh name="lower_teeht_krishna_model_iTeeth_toungteethSG1_0" geometry={nodes.lower_teeht_krishna_model_iTeeth_toungteethSG1_0.geometry} material={materials['krishna_model_i:Teeth_toung:teethSG1']} skeleton={nodes.lower_teeht_krishna_model_iTeeth_toungteethSG1_0.skeleton} />
          <skinnedMesh name="main_dhoti_krishna_model_iDhoti_Bottom_0" geometry={nodes.main_dhoti_krishna_model_iDhoti_Bottom_0.geometry} material={materials['krishna_model_i:Dhoti_Bottom']} skeleton={nodes.main_dhoti_krishna_model_iDhoti_Bottom_0.skeleton} />
          <skinnedMesh name="Toung_krishna_model_iTeeth_tounggumSG1_0" geometry={nodes.Toung_krishna_model_iTeeth_tounggumSG1_0.geometry} material={materials['krishna_model_i:Teeth_toung:gumSG1']} skeleton={nodes.Toung_krishna_model_iTeeth_tounggumSG1_0.skeleton} />
          <skinnedMesh name="upper_teeth1_krishna_model_iTeeth_tounggumSG1_0" geometry={nodes.upper_teeth1_krishna_model_iTeeth_tounggumSG1_0.geometry} material={materials['krishna_model_i:Teeth_toung:gumSG1']} skeleton={nodes.upper_teeth1_krishna_model_iTeeth_tounggumSG1_0.skeleton} />
          <skinnedMesh name="upper_teeth1_krishna_model_iTeeth_toungteethSG1_0" geometry={nodes.upper_teeth1_krishna_model_iTeeth_toungteethSG1_0.geometry} material={materials['krishna_model_i:Teeth_toung:teethSG1']} skeleton={nodes.upper_teeth1_krishna_model_iTeeth_toungteethSG1_0.skeleton} />
        </group>
      </group>
    </group>
  )
}
