/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/mcDonalds.glb -o ./src/ModernCity/Models/mcDonalds.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function McDonalds(props) {
  const { nodes, materials } = useGLTF('/mcDonalds.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.399, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={8.869}>
        <group scale={2}>
          <mesh geometry={nodes.Plane003_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Plane003_2.geometry} material={materials['Material.005']} />
        </group>
        <mesh geometry={nodes.Plane_0.geometry} material={materials['Material.004']} position={[0, 0, -0.016]} scale={2.6} />
        <mesh geometry={nodes.Plane001_0.geometry} material={materials['Material.010']} position={[-1.749, -2.093, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.3} />
      </group>
    </group>
  )
}
